"use client";

import { getUserRole } from "@/app/utils/auth.utils";
import Header from "@/components/layout/Header";
import MainSidebar from "@/components/layout/MainSidebar";
import NotificationsBar from "@/components/layout/NotificationsBar";
import {
  Sidebar,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { useRouter } from "@/i18n/navigation";
import type { Metadata } from "next";
import { useLocale } from "next-intl";
import { useEffect } from "react";

// export const metadata: Metadata = {
//   title: "Enjaz Dashboard",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();

  const router = useRouter();
  const role = getUserRole();

  useEffect(() => {
    if (!role) {
      router.push("/login");
    }
  }, [role, router]);

  if (!role) {
    return null;
  }

  return (
    <SidebarProvider>
      <Sidebar side={locale === "en" ? "left" : "right"}>
        <MainSidebar />
      </Sidebar>

      <div className="grow flex flex-col">
        <SidebarTrigger className="md:hidden m-4" />
        <Header />

        <div className="main-content min-h-screen bg-global-bg p-4 md:p-10">
          {children}
        </div>
      </div>

      <div className="hidden xl:block">
        <Sidebar side={locale === "en" ? "right" : "left"} collapsible="none">
          <NotificationsBar />
        </Sidebar>
      </div>
    </SidebarProvider>
  );
}
